# Generated by Django 3.1.1 on 2020-11-02 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='in_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept', to='client.company'),
        ),
    ]
